version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: stremio-panel-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=stremio
      - MONGO_INITDB_ROOT_PASSWORD=stremiopassword
    networks:
      - stremio-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stremio-panel-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://stremio:stremiopassword@mongodb:27017/stremio-panel?authSource=admin
      - JWT_SECRET=your_jwt_secret_change_this_in_production
      - JWT_EXPIRES_IN=7d
      - STREMIO_API_URL=https://api.strem.io
    ports:
      - "5000:5000"
    networks:
      - stremio-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stremio-panel-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - stremio-network

networks:
  stremio-network:
    driver: bridge

volumes:
  mongodb_data: